### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by astronomersiva** [astronomersiva/Map-My-Problems#3]
- [x] Give level based authentication to admins.
- [ ] Provide a way to export/import JSON/CSV.
- [x] Extract key words and display as trending topics.
- [x] Remove all admin login links from the application and make it a standalone application.
- [ ] Write a script to automatically setup the requirements and the DB.
- [ ] Add Tamil translations.

**Comment by astronomersiva** [comment]
@vignesh17 would you like to take up adding Tamil translations?

**Comment by vignesh17** [comment]
Tk siva. I will take care of tamil translation

**Comment by astronomersiva** [comment]
@vignesh17 Any progress?
